spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 600000        # 10 min por defecto
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_MOVIES_URL:jdbc:mysql://localhost:3306/movies_db?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USER:root}
    password: ${DB_PASS:1234}
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: ${JWT_SECRET:2da08e8ee264a149413ce46abebbd566b4c8bbb019b37708ed9d77f8511ac7bf}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} - %logger{36} - [%X{correlationId}] - %msg%n"
  level:
    root: WARN
    com.estebanmm13.movies_service: DEBUG
    org.hibernate: ERROR
    org.springframework: ERROR
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: movies-service

resilience4j:
  circuitbreaker:
    instances:
      auth-service-cb:
        sliding-window-size: 5
        failure-rate-threshold: 60
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        register-health-indicator: true
  retry:
    instances:
      auth-service-retry:
        max-attempts: 2
        wait-duration: 200ms